<?php

$HOST = "RK02";
$USERNAME = "sa";
$PASSWORD = "Fpce#9084";
$DATABASE = "TEST_EMS2";

$HOST_OLD = "RK02";
$USERNAME_OLD = "sa";
$PASSWORD_OLD = 'Fpce#9084';
$DATABASE_OLD = "RTMS"; 

$HOST_TMS = "RK01";
$USERNAME_TMS = "sa";
$PASSWORD_TMS = 'Fpce#9084';
$DATABASE_TMS = "RTMS";